# docker-compose.yml
version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: local-board-db
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root  # 로컬용 비번
      MYSQL_DATABASE: board_dev  # 생성할 DB 이름
      TZ: Asia/Seoul
    volumes:
      - ./db/data:/var/lib/mysql # 로컬 폴더에 데이터 저장
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci