spring:
  application:
    name: trend-board
  profiles:
    default: local
  flyway:
    enabled: false
    locations: classpath:db/migration

management:
  endpoints:
    web:
      exposure:
        include: health,info
